Extension { #name : #Morph }

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/15/2024 21:57'
}
Morph >> isEPGBacklogCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/15/2024 22:46'
}
Morph >> isEPGBugCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 5/27/2024 17:58'
}
Morph >> isEPGDnDArea [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/23/2024 14:22'
}
Morph >> isEPGDnDMorph [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/23/2024 14:22'
}
Morph >> isEPGEventCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/15/2024 22:46'
}
Morph >> isEPGFeatureCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/15/2024 22:46'
}
Morph >> isEPGStorypoint [

	^ false.
]
