Extension { #name : #Morph }

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/11/2024 10:29'
}
Morph >> isEPGBugCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 5/27/2024 17:58'
}
Morph >> isEPGDnDArea [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 5/27/2024 13:39'
}
Morph >> isEPGDnDMorph [
	^false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/11/2024 10:29'
}
Morph >> isEPGFeatureCard [

	^ false.
]

{
	#category : #'*ExtremeProGaming',
	#'squeak_changestamp' : 'HCH 6/11/2024 10:29'
}
Morph >> isEPGStorypoint [

	^ false.
]
