Class {
	#name : #Test,
	#superclass : #Morph,
	#category : #ExtremeProGaming
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'sv 6/15/2024 18:04'
}
Test >> handleMouseDown: anEvent [

	^true
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'sv 6/15/2024 18:08'
}
Test >> handlesMouseDown: anEvent [

	^true
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'sv 6/15/2024 18:04'
}
Test >> mouseDown: anEvent [

	self halt.
]
